### ISSUE TITLE
Ever Use a Projection Head?

### ISSUE THREAD

**Issue by DarrenZhang01** [YannDubs/lossyless#41]
Hi Yann, 

Did you ever use a **project head** [1] (i.e., a multi-layer perceptron) to transform the output of the encoder? 

If I understand correctly, you directly feed the output of the encoder (e.g., a pre-trained ResNet model) into the rate estimator?

Thanks!

Reference: 

[1] Chen, T., Kornblith, S., Norouzi, M., & Hinton, G. (2020, November). A simple framework for contrastive learning of visual representations. In International conference on machine learning (pp. 1597-1607). PMLR.

**Comment by YannDubs** [comment]
We apply a projection head here : https://github.com/YannDubs/lossyless/blob/462af23a52d68f860e5ae2ff9c59f04cfb8c5fd5/lossyless/distortions.py#L314

this is only needed for the contrastive loss. What you send this the representation not the projected version. Classification performance from the projected version is much lower
