### ISSUE TITLE
requirements issue

### ISSUE THREAD

**Issue by ildmxGL** [YannDubs/lossyless#43]
Hello, I would like to run your minimal code, but I need help with the environment setup. Could you provide the exact version of the library?

**Comment by YannDubs** [comment]
did you have issues when installing `pip install -r requirements.txt`? If so can you link to the issue

**Comment by ildmxGL** [comment]
I've tried using Colab, referred to "installation details", and even attempted `pip install -r requirements.txt`, but the code still doesn't run smoothly. When I downgraded the torch version to 1.7.1, I got the msg that the bottleneck's size didn't match.

**Comment by ildmxGL** [comment]
I solved it by checking the requirements/environment.yaml. Thank you for your interest.
